"""Public API for the standalone, unofficial RMUC 2026 MuJoCo field loader."""

from .builder import BuilderUnavailable, build_from_official_step, build_runtime_asset_pack
from .boundary_guard import FieldBoundaryGuard
from .download import (
    LAST_REVIEWED_RULEBOOK_PUBLICATION_DATE,
    LAST_REVIEWED_RULEBOOK_SHA256,
    LAST_REVIEWED_RULEBOOK_SIZE,
    LAST_REVIEWED_RULEBOOK_URL,
    LAST_REVIEWED_RULEBOOK_VERSION,
    LAST_RULE_REVIEW_DATE,
    OFFICIAL_RULE_CENTRE,
    OFFICIAL_SOURCE_PAGE,
    OFFICIAL_STEP_PRODUCT,
    OFFICIAL_STEP_SHA256,
    OFFICIAL_STEP_SIZE,
    OFFICIAL_STEP_URL,
    DownloadedStep,
    DownloadError,
    download_official_step,
    verify_official_step,
)
from .display import FieldDisplayController
from .control import ControlCallback, NoOpController, load_controller
from .energy_unit import add_energy_unit, load_field_with_energy_unit
from .errors import (
    AssetIntegrityError,
    ManifestError,
    MujocoModelError,
    OutOfBoundsError,
    Rmuc2026Error,
)
from .manifest import (
    DEFAULT_RUNTIME_PROFILE,
    RUNTIME_ARTIFACT_TYPE,
    RUNTIME_PROFILE_NAMES,
    FieldAsset,
    ValidationReport,
    verify_asset,
)
from .jump_probe import (
    JumpProbeConfig,
    LandingProfile,
    measure_runtime_landing_profile,
    run_fixed_fly_ramp_jump_probe,
)
from .mjcf import (
    FIELD_ATTACH_PREFIX,
    FIELD_COLLISION_GEOM_NAME,
    HFIELD_NAME,
    UNOFFICIAL_FRICTION_PRESETS,
    apply_friction_preset,
    compose_with_robot,
    inject_exact_heightfield,
    load_model,
)
from .isaac import IsaacHeightfieldInput, load_isaac_heightfield
from .perimeter_fence import export_fenced_pack, perimeter_fence_contract
from .query import (
    HEIGHTFIELD_CLAIM_BOUNDARY,
    MAX_SPAWN_CANDIDATES,
    HeightFieldData,
    SpawnCandidate,
    SurfaceSample,
    field_bounds,
    find_spawn_candidates,
    height_at,
    load_heightfield,
    surface_at,
)
from .ramp_source_audit import audit_fly_ramp_source_overlap
from .scenarios import SCENARIOS, ScenarioSpec, get_scenario, list_scenarios, scenario_descriptor
from .training import MuJoCoScenario, StepResult, TelemetryRecorder
from .turning import (
    NoOpTurnController,
    TurnCommand,
    TurnController,
    TurnEpisodeResult,
    TurnPhase,
    TurnSpawn,
    load_turn_controller,
    reset_turn_spawn,
    run_turn_batch,
    run_turn_episode,
    screen_turn_spawns,
    turn_phase,
    turn_phase_registry,
    turn_spawn_manifest,
)

__all__ = [
    "AssetIntegrityError",
    "BuilderUnavailable",
    "DownloadedStep",
    "DownloadError",
    "DEFAULT_RUNTIME_PROFILE",
    "FIELD_ATTACH_PREFIX",
    "FIELD_COLLISION_GEOM_NAME",
    "FieldAsset",
    "FieldBoundaryGuard",
    "FieldDisplayController",
    "ControlCallback",
    "NoOpController",
    "HEIGHTFIELD_CLAIM_BOUNDARY",
    "HFIELD_NAME",
    "HeightFieldData",
    "IsaacHeightfieldInput",
    "LAST_REVIEWED_RULEBOOK_PUBLICATION_DATE",
    "LAST_REVIEWED_RULEBOOK_SHA256",
    "LAST_REVIEWED_RULEBOOK_SIZE",
    "LAST_REVIEWED_RULEBOOK_URL",
    "LAST_REVIEWED_RULEBOOK_VERSION",
    "LAST_RULE_REVIEW_DATE",
    "JumpProbeConfig",
    "LandingProfile",
    "ManifestError",
    "MAX_SPAWN_CANDIDATES",
    "MujocoModelError",
    "OFFICIAL_SOURCE_PAGE",
    "OFFICIAL_RULE_CENTRE",
    "OFFICIAL_STEP_PRODUCT",
    "OFFICIAL_STEP_SHA256",
    "OFFICIAL_STEP_SIZE",
    "OFFICIAL_STEP_URL",
    "OutOfBoundsError",
    "RUNTIME_ARTIFACT_TYPE",
    "RUNTIME_PROFILE_NAMES",
    "Rmuc2026Error",
    "MuJoCoScenario",
    "SCENARIOS",
    "ScenarioSpec",
    "SpawnCandidate",
    "StepResult",
    "SurfaceSample",
    "ValidationReport",
    "UNOFFICIAL_FRICTION_PRESETS",
    "TelemetryRecorder",
    "apply_friction_preset",
    "audit_fly_ramp_source_overlap",
    "add_energy_unit",
    "build_from_official_step",
    "build_runtime_asset_pack",
    "compose_with_robot",
    "download_official_step",
    "field_bounds",
    "export_fenced_pack",
    "find_spawn_candidates",
    "height_at",
    "inject_exact_heightfield",
    "load_heightfield",
    "load_field_with_energy_unit",
    "load_model",
    "load_controller",
    "load_turn_controller",
    "load_isaac_heightfield",
    "get_scenario",
    "list_scenarios",
    "measure_runtime_landing_profile",
    "perimeter_fence_contract",
    "run_fixed_fly_ramp_jump_probe",
    "run_turn_batch",
    "run_turn_episode",
    "reset_turn_spawn",
    "screen_turn_spawns",
    "surface_at",
    "scenario_descriptor",
    "NoOpTurnController",
    "TurnCommand",
    "TurnController",
    "TurnEpisodeResult",
    "TurnPhase",
    "TurnSpawn",
    "turn_phase",
    "turn_phase_registry",
    "turn_spawn_manifest",
    "verify_asset",
    "verify_official_step",
]

__version__ = "1.0.0"
