"""Public API for the standalone, unofficial RMUC 2026 MuJoCo field loader."""

from .builder import BuilderUnavailable, build_from_official_step, build_runtime_asset_pack
from .boundary_guard import FieldBoundaryGuard
from .download import (
    LAST_REVIEWED_RULEBOOK_PUBLICATION_DATE,
    LAST_REVIEWED_RULEBOOK_SHA256,
    LAST_REVIEWED_RULEBOOK_SIZE,
    LAST_REVIEWED_RULEBOOK_URL,
    LAST_REVIEWED_RULEBOOK_VERSION,
    LAST_RULE_REVIEW_DATE,
    OFFICIAL_RULE_CENTRE,
    OFFICIAL_SOURCE_PAGE,
    OFFICIAL_STEP_PRODUCT,
    OFFICIAL_STEP_SHA256,
    OFFICIAL_STEP_SIZE,
    OFFICIAL_STEP_URL,
    DownloadedStep,
    DownloadError,
    download_official_step,
    verify_official_step,
)
from .display import FieldDisplayController
from .energy_unit import add_energy_unit, load_field_with_energy_unit
from .errors import (
    AssetIntegrityError,
    ManifestError,
    MujocoModelError,
    OutOfBoundsError,
    Rmuc2026Error,
)
from .manifest import (
    DEFAULT_RUNTIME_PROFILE,
    RUNTIME_ARTIFACT_TYPE,
    RUNTIME_PROFILE_NAMES,
    FieldAsset,
    ValidationReport,
    verify_asset,
)
from .mjcf import (
    FIELD_ATTACH_PREFIX,
    FIELD_COLLISION_GEOM_NAME,
    HFIELD_NAME,
    UNOFFICIAL_FRICTION_PRESETS,
    apply_friction_preset,
    compose_with_robot,
    inject_exact_heightfield,
    load_model,
)
from .query import (
    HEIGHTFIELD_CLAIM_BOUNDARY,
    MAX_SPAWN_CANDIDATES,
    HeightFieldData,
    SpawnCandidate,
    SurfaceSample,
    field_bounds,
    find_spawn_candidates,
    height_at,
    load_heightfield,
    surface_at,
)

__all__ = [
    "AssetIntegrityError",
    "BuilderUnavailable",
    "DownloadedStep",
    "DownloadError",
    "DEFAULT_RUNTIME_PROFILE",
    "FIELD_ATTACH_PREFIX",
    "FIELD_COLLISION_GEOM_NAME",
    "FieldAsset",
    "FieldBoundaryGuard",
    "FieldDisplayController",
    "HEIGHTFIELD_CLAIM_BOUNDARY",
    "HFIELD_NAME",
    "HeightFieldData",
    "LAST_REVIEWED_RULEBOOK_PUBLICATION_DATE",
    "LAST_REVIEWED_RULEBOOK_SHA256",
    "LAST_REVIEWED_RULEBOOK_SIZE",
    "LAST_REVIEWED_RULEBOOK_URL",
    "LAST_REVIEWED_RULEBOOK_VERSION",
    "LAST_RULE_REVIEW_DATE",
    "ManifestError",
    "MAX_SPAWN_CANDIDATES",
    "MujocoModelError",
    "OFFICIAL_SOURCE_PAGE",
    "OFFICIAL_RULE_CENTRE",
    "OFFICIAL_STEP_PRODUCT",
    "OFFICIAL_STEP_SHA256",
    "OFFICIAL_STEP_SIZE",
    "OFFICIAL_STEP_URL",
    "OutOfBoundsError",
    "RUNTIME_ARTIFACT_TYPE",
    "RUNTIME_PROFILE_NAMES",
    "Rmuc2026Error",
    "SpawnCandidate",
    "SurfaceSample",
    "ValidationReport",
    "UNOFFICIAL_FRICTION_PRESETS",
    "apply_friction_preset",
    "add_energy_unit",
    "build_from_official_step",
    "build_runtime_asset_pack",
    "compose_with_robot",
    "download_official_step",
    "field_bounds",
    "find_spawn_candidates",
    "height_at",
    "inject_exact_heightfield",
    "load_heightfield",
    "load_field_with_energy_unit",
    "load_model",
    "surface_at",
    "verify_asset",
    "verify_official_step",
]

__version__ = "0.3.0a1"
